# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zulun/Project/Agenda

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zulun/Project/Agenda

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zulun/Project/Agenda/CMakeFiles /home/zulun/Project/Agenda/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zulun/Project/Agenda/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named agenda

# Build rule for target.
agenda: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 agenda
.PHONY : agenda

# fast build rule for target.
agenda/fast:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/build
.PHONY : agenda/fast

agenda.o: agenda.cpp.o

.PHONY : agenda.o

# target to build an object file
agenda.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/agenda.cpp.o
.PHONY : agenda.cpp.o

agenda.i: agenda.cpp.i

.PHONY : agenda.i

# target to preprocess a source file
agenda.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/agenda.cpp.i
.PHONY : agenda.cpp.i

agenda.s: agenda.cpp.s

.PHONY : agenda.s

# target to generate assembly for a file
agenda.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/agenda.cpp.s
.PHONY : agenda.cpp.s

config.o: config.cpp.o

.PHONY : config.o

# target to build an object file
config.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/config.cpp.o
.PHONY : config.cpp.o

config.i: config.cpp.i

.PHONY : config.i

# target to preprocess a source file
config.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/config.cpp.i
.PHONY : config.cpp.i

config.s: config.cpp.s

.PHONY : config.s

# target to generate assembly for a file
config.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/config.cpp.s
.PHONY : config.cpp.s

mylib.o: mylib.cpp.o

.PHONY : mylib.o

# target to build an object file
mylib.cpp.o:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/mylib.cpp.o
.PHONY : mylib.cpp.o

mylib.i: mylib.cpp.i

.PHONY : mylib.i

# target to preprocess a source file
mylib.cpp.i:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/mylib.cpp.i
.PHONY : mylib.cpp.i

mylib.s: mylib.cpp.s

.PHONY : mylib.s

# target to generate assembly for a file
mylib.cpp.s:
	$(MAKE) -f CMakeFiles/agenda.dir/build.make CMakeFiles/agenda.dir/mylib.cpp.s
.PHONY : mylib.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... agenda"
	@echo "... agenda.o"
	@echo "... agenda.i"
	@echo "... agenda.s"
	@echo "... config.o"
	@echo "... config.i"
	@echo "... config.s"
	@echo "... mylib.o"
	@echo "... mylib.i"
	@echo "... mylib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

